# keep [] for all worlds
directly_in_inventory_worlds:
  - "SuperiorWorld"

# keep [] for all worlds
disable_teleport_worlds:
  - "SuperiorWorld"

# keep [] for all worlds
disable_piston_push_worlds:
  - "SuperiorWorld"

sounds:
  pickup: ENTITY_ITEM_PICKUP
  interact: BLOCK_STONE_BREAK
  cancel: BLOCK_ANVIL_BREAK

messages:
  cannot_place: "&7[&c&lES&7] &cVous ne pouvez pas placer l'Oeuf de Dragon !"
  cannot_break: "&7[&c&lES&7] &cVous ne pouvez pas casser l'Oeuf de Dragon !"
  success_break: "&7[&c&lES&7] &aVotre Oeuf de Dragon vient de vous être donné !"
  success_break_drop: "&7[&c&lES&7] &aVous n'avez plus de place, l'Oeuf de Dragon vient de tomber au sol !"